#!/bin/bash
# These functions use a vault named `dev`.
# Create the vault like this: `op vault create dev`

# Enable completion for 1Password CLI.
. <(op completion bash)


# Usage: export-secret [VAR]..
# ----------------------------------------------------------------------
# Export secrets into environment variables.
function export-secret() {
    local variable=

    for variable
    do
        printf -v "$variable" '%s' "$(op read op://dev/$variable/password)"
        export "$variable"
    done
}

# Usage: list-secrets
# ----------------------------------------------------------------------
# List secrets.
function list-secrets() {
    op item list --vault dev --format=json | jq -r ".[].title"
}

# Usage: store-secret VAR VALUE
# ----------------------------------------------------------------------
# Store a secret.
function store-secret() {
    local variable="$1"
    shift

    local value="$1"
    shift

    op item create \
       --vault dev \
       --category password \
       --title "$variable" \
       password="$value"
}
