#!/bin/bash
# Enable completion for 1Password CLI.
. <(op completion bash)

# op vault create dev
# op item create --vault dev --category password --title NAME password=VALUE

# Usage: export-secret [VAR]..
# ----------------------------------------------------------------------
# Export secrets into environment variables.
function export-secret() {
    local variable=

    for variable
    do
        printf -v "$variable" '%s' "$(op read op://dev/$variable/password)"
    done

    export "$variable"
}


