#!/bin/bash
prepend PATH ~/.local/bin
prepend CDPATH ~/Code/* .

# Use emacs to edit files.
export VISUAL=emacsclient
export EDITOR=emacsclient

# Use bat to view manpages (aka batman).
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# Enable color theme for file listings.
export LS_COLORS="$(vivid generate iceberg-dark)"
export EXA_COLORS="\
:da=38;5;58\
:uu=38;5;31\
:ur=38;5;215\
:uw=38;5;202\
:ux=38;5;208\
:ue=38;5;208\
:gr=38;5;214\
:gw=38;5;202\
:gx=38;5;208\
:tr=38;5;214\
:tw=38;5;202\
:tx=38;5;208\
:sn=38;5;70\
:sb=38;5;28"

# Enable globstar.
shopt -s globstar

# Support ^L in vi mode.
bind -m vi-command 'Control-l: clear-screen'
bind -m vi-insert 'Control-l: clear-screen'
