alias -- -='cd -'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias e='envvars'
alias g='git graph'
alias d='dirs -v'
alias cp='cp --verbose --interactive'
alias ls='exa --icons'
alias la='exa --icons --all'
alias ll='exa --icons --all --long --time-style=long-iso'
alias lst='ls --tree'
alias llt='ll --tree'
alias mv='mv --verbose --interactive'
alias pd=pushd
alias edit=$EDITOR
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias mkdir='mkdir --verbose --parents'
alias path='echo -e ${PATH//:/\\n}'
alias cat='bat -p'
alias diff='batdiff'
alias tree='exatree'
alias -- -h='usage'
alias -- --help='usage'

