(global-set-key "\C-c." 'find-emacs-conf)
(global-set-key "\C-c:" 'reload-emacs-conf)
(global-set-key "\C-ca" 'align)
(global-set-key "\C-cb" 'recompile)
(global-set-key "\C-cc" 'comment-dwim)
(global-set-key "\C-cg" 'goto-line)
(global-set-key "\C-ci" 'indent-region)
(global-set-key "\C-ck" 'kill-unmodified-buffers)
(global-set-key "\C-cm" (lambda () (interactive) (manual-entry (current-word))))
(global-set-key "\C-cr" 'revert-buffer)
(global-set-key "\C-cs" 'save-macro)
(global-set-key "\C-ct" 'untabify-buffer)
(global-set-key "\C-cv" 'View-back-to-mark)
(global-set-key "\C-cz" 'shell)
(global-set-key "\M-n" 'scroll-up-1)
(global-set-key "\M-p" 'scroll-down-1)
(global-set-key "\M-N" 'scroll-up)
(global-set-key "\M-P" 'scroll-down)
(global-unset-key "\C-x\C-c")
(global-set-key   "\C-x\C-c\C-v" 'save-buffers-kill-emacs)
(global-set-key (kbd "C-c +") 'increment-number-at-point)
(global-set-key (kbd "C-c -") 'decrement-number-at-point)
